### gonna use this notebook for project stuff

In [1]:
import pandas as pd
import numpy as np

In [26]:
df = pd.read_csv("ecs171_data.csv", sep=";")
df.columns = df.columns.str.replace('\t', '', regex=False)

cat_info_num = df[['Marital status', 'Application mode', 'Course','Previous qualification', 'Nacionality', 
               "Mother's qualification", "Father's qualification", "Mother's occupation", "Father's occupation", "Target"]]
cat_info_num

,Marital status,Application mode,Course,Previous qualification,Nacionality,Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,Target
0,1,17,171,1,1,19,12,5,9,Dropout
1,1,15,9254,1,1,1,3,3,3,Graduate
2,1,1,9070,1,1,37,37,9,9,Dropout
3,1,17,9773,1,1,38,37,5,3,Graduate
4,2,39,8014,1,1,37,38,9,9,Graduate
...,...,...,...,...,...,...,...,...,...,...
4419,1,1,9773,1,1,1,1,5,4,Graduate
4420,1,1,9773,1,105,1,1,9,9,Dropout
4421,1,1,9500,1,1,37,37,9,9,Dropout
4422,1,1,9147,1,1,37,37,7,4,Graduate
4423,1,10,9773,1,22,38,37,5,9,Graduate

In [25]:
### maps (numerical to categorical)

marital_status_map = {
    1: "Single",
    2: "Married",
    3: "Widower",
    4: "Divorced",
    5: "Facto union",
    6: "Legally separated"
}

application_mode_map = {
    1: "1st phase - general contingent",
    2: "Ordinance No. 612/93",
    5: "1st phase - special contingent (Azores Island)",
    7: "Holders of other higher courses",
    10: "Ordinance No. 854-B/99",
    15: "International student (bachelor)",
    16: "1st phase - special contingent (Madeira Island)",
    17: "2nd phase - general contingent",
    18: "3rd phase - general contingent",
    26: "Ordinance No. 533-A/99 item b2 (Different Plan)",
    27: "Ordinance No. 533-A/99 item b3 (Other Institution)",
    39: "Over 23 years old",
    42: "Transfer",
    43: "Change of course",
    44: "Technological specialization diploma holders",
    51: "Change of institution/course",
    53: "Short cycle diploma holders",
    57: "Change of institution/course (International)"
}

course_map = {
    33: "Biofuel Production Technologies",
    171: "Animation and Multimedia Design",
    8014: "Social Service (evening attendance)",
    9003: "Agronomy",
    9070: "Communication Design",
    9085: "Veterinary Nursing",
    9119: "Informatics Engineering",
    9130: "Equinculture",
    9147: "Management",
    9238: "Social Service",
    9254: "Tourism",
    9500: "Nursing",
    9556: "Oral Hygiene",
    9670: "Advertising and Marketing Management",
    9773: "Journalism and Communication",
    9853: "Basic Education",
    9991: "Management (evening attendance)"
}

previous_qualification_map = {
    1: "Secondary education",
    2: "Higher education - bachelor's degree",
    3: "Higher education - degree",
    4: "Higher education - master's",
    5: "Higher education - doctorate",
    6: "Frequency of higher education",
    9: "12th year - not completed",
    10: "11th year - not completed",
    12: "Other - 11th year",
    14: "10th year",
    15: "10th year - not completed",
    19: "Basic education 3rd cycle",
    38: "Basic education 2nd cycle",
    39: "Technological specialization course",
    40: "Higher education - degree (1st cycle)",
    42: "Professional higher technical course",
    43: "Higher education - master (2nd cycle)"
}

nationality_map = {
    1: "Portuguese",
    2: "German",
    6: "Spanish",
    11: "Italian",
    13: "Dutch",
    14: "English",
    17: "Lithuanian",
    21: "Angolan",
    22: "Cape Verdean",
    24: "Guinean",
    25: "Mozambican",
    26: "Santomean",
    32: "Turkish",
    41: "Brazilian",
    62: "Romanian",
    100: "Moldova",
    101: "Mexican",
    103: "Ukrainian",
    105: "Russian",
    108: "Cuban",
    109: "Colombian"
}

# used for father and mother
qualification_map = { 
    1: "Secondary Education - 12th Year",
    2: "Higher Education - Bachelor's",
    3: "Higher Education - Degree",
    4: "Higher Education - Master's",
    5: "Higher Education - Doctorate",
    6: "Frequency of Higher Education",
    9: "12th Year - Not Completed",
    10: "11th Year - Not Completed",
    11: "7th Year (Old)",
    12: "Other - 11th Year",
    13: "2nd year complementary high school",
    14: "10th Year",
    18: "General commerce course",
    19: "Basic Education 3rd Cycle",
    20: "Complementary High School Course",
    22: "Technical-professional course",
    25: "Complementary High School - Not concluded",
    26: "7th Year",
    27: "2nd cycle general high school",
    29: "9th Year - Not Completed",
    30: "8th Year",
    31: "Administration and Commerce",
    33: "Supplementary Accounting and Administration",
    34: "Unknown",
    35: "Can't read or write",
    36: "Can read without 4th year",
    37: "Basic education 1st cycle",
    38: "Basic Education 2nd Cycle",
    39: "Technological specialization",
    40: "Higher education - degree (1st cycle)",
    41: "Specialized higher studies",
    42: "Professional higher technical",
    43: "Higher Education - Master (2nd cycle)",
    44: "Higher Education - Doctorate (3rd cycle)"
}

# used for father and mother
occupation_map = {
    0: "Student",
    1: "Directors and Executive Managers",
    2: "Intellectual and Scientific Specialists",
    3: "Intermediate Level Technicians",
    4: "Administrative staff",
    5: "Service and Sales Workers",
    6: "Agriculture/Fisheries Skilled Workers",
    7: "Industry and Construction Skilled Workers",
    8: "Machine Operators",
    9: "Unskilled Workers",
    10: "Armed Forces",
    90: "Other Situation",
    99: "Blank",
    101: "Armed Forces Officers",
    102: "Armed Forces Sergeants",
    103: "Other Armed Forces personnel",
    112: "Administrative and commercial directors",
    114: "Hospitality directors",
    121: "Science and engineering specialists",
    122: "Health professionals",
    123: "Teachers",
    124: "Finance and accounting specialists",
    125: "ICT Specialists",
    131: "Science and engineering technicians",
    132: "Health technicians",
    134: "Legal/social/cultural technicians",
    135: "ICT technicians",
    141: "Office workers",
    143: "Accounting and registry operators",
    144: "Administrative support",
    151: "Personal service workers",
    152: "Sellers",
    153: "Personal care workers",
    154: "Security personnel",
    161: "Market-oriented farmers",
    163: "Subsistence farmers/fishers",
    171: "Skilled construction workers",
    172: "Metalworking skilled workers",
    173: "Printing and craft workers",
    174: "Electrical skilled workers",
    175: "Food/clothing industry workers",
    181: "Plant and machine operators",
    182: "Assembly workers",
    183: "Drivers and mobile operators",
    191: "Cleaning workers",
    192: "Unskilled agriculture workers",
    193: "Unskilled industry workers",
    194: "Meal preparation assistants",
    195: "Street vendors"
}

In [31]:
mappings = {
    "Marital status": marital_status_map,
    "Application mode": application_mode_map,
    "Course": course_map,
    "Previous qualification": previous_qualification_map,
    "Nacionality": nationality_map,
    "Mother's qualification": qualification_map,
    "Father's qualification": qualification_map,
    "Mother's occupation": occupation_map,
    "Father's occupation": occupation_map,
} # map of maps

for col, mapping in mappings.items():
    df[col + "_label"] = df[col].astype(int).map(mapping).astype("category")

cat_info_fixed_cols = [col for col in df.columns if "_label" in col]
cat_info_fixed = df[cat_info_fixed_cols + ["Target"]]
cat_info_fixed

,Marital status_label,Application mode_label,Course_label,Previous qualification_label,Nacionality_label,Mother's qualification_label,Father's qualification_label,Mother's occupation_label,Father's occupation_label,Target
0,Single,2nd phase - general contingent,Animation and Multimedia Design,Secondary education,Portuguese,Basic Education 3rd Cycle,Other - 11th Year,Service and Sales Workers,Unskilled Workers,Dropout
1,Single,International student (bachelor),Tourism,Secondary education,Portuguese,Secondary Education - 12th Year,Higher Education - Degree,Intermediate Level Technicians,Intermediate Level Technicians,Graduate
2,Single,1st phase - general contingent,Communication Design,Secondary education,Portuguese,Basic education 1st cycle,Basic education 1st cycle,Unskilled Workers,Unskilled Workers,Dropout
3,Single,2nd phase - general contingent,Journalism and Communication,Secondary education,Portuguese,Basic Education 2nd Cycle,Basic education 1st cycle,Service and Sales Workers,Intermediate Level Technicians,Graduate
4,Married,Over 23 years old,Social Service (evening attendance),Secondary education,Portuguese,Basic education 1st cycle,Basic Education 2nd Cycle,Unskilled Workers,Unskilled Workers,Graduate
...,...,...,...,...,...,...,...,...,...,...
4419,Single,1st phase - general contingent,Journalism and Communication,Secondary education,Portuguese,Secondary Education - 12th Year,Secondary Education - 12th Year,Service and Sales Workers,Administrative staff,Graduate
4420,Single,1st phase - general contingent,Journalism and Communication,Secondary education,Russian,Secondary Education - 12th Year,Secondary Education - 12th Year,Unskilled Workers,Unskilled Workers,Dropout
4421,Single,1st phase - general contingent,Nursing,Secondary education,Portuguese,Basic education 1st cycle,Basic education 1st cycle,Unskilled Workers,Unskilled Workers,Dropout
4422,Single,1st phase - general contingent,Management,Secondary education,Portuguese,Basic education 1st cycle,Basic education 1st cycle,Industry and Construction Skilled Workers,Administrative staff,Graduate
4423,Single,Ordinance No. 854-B/99,Journalism and Communication,Secondary education,Cape Verdean,Basic Education 2nd Cycle,Basic education 1st cycle,Service and Sales Workers,Unskilled Workers,Graduate

In [42]:
cross_tables = {}

for col in cat_info_fixed_cols:
    counts = pd.crosstab(df[col], df["Target"])
    percents = pd.crosstab(df[col], df["Target"], normalize="index")
    table = counts.astype(str) + " (" + (percents * 100).round(1).astype(str) + "%)"
    cross_tables[col] = table

for col in cat_info_fixed_cols:
    print(cross_tables[col])
    print()

Target                     Dropout     Enrolled      Graduate
Marital status_label
Divorced                42 (46.2%)   16 (17.6%)    33 (36.3%)
Facto union             11 (44.0%)    3 (12.0%)    11 (44.0%)
Legally separated        4 (66.7%)    1 (16.7%)     1 (16.7%)
Married                179 (47.2%)   52 (13.7%)   148 (39.1%)
Single                1184 (30.2%)  720 (18.4%)  2015 (51.4%)
Widower                  1 (25.0%)    2 (50.0%)     1 (25.0%)

Target                                                  Dropout     Enrolled  \
Application mode_label
1st phase - general contingent                      345 (20.2%)  300 (17.6%)
1st phase - special contingent (Azores Island)        2 (12.5%)    8 (50.0%)
1st phase - special contingent (Madeira Island)       5 (13.2%)    8 (21.1%)
2nd phase - general contingent                      256 (29.4%)  159 (18.2%)
3rd phase - general contingent                       45 (36.3%)   16 (12.9%)
Change of course                                    115 (36.9%)   75 (24.0%)
Change of institution/course                         20 (33.9%)   13 (22.0%)
Change of institution/course (International)           0 (0.0%)     0 (0.0%)
Holders of other higher courses                      85 (61.2%)     7 (5.0%)
International student (bachelor)                      5 (16.7%)   10 (33.3%)
Ordinance No. 533-A/99 item b2 (Different Plan)      1 (100.0%)     0 (0.0%)
Ordinance No. 533-A/99 item b3 (Other Institution)   1 (100.0%)     0 (0.0%)
Ordinance No. 612/93                                  2 (66.7%)     0 (0.0%)
Ordinance No. 854-B/99                                3 (30.0%)     0 (0.0%)
Over 23 years old                                   435 (55.4%)  121 (15.4%)
Short cycle diploma holders                           4 (11.4%)   10 (28.6%)
Technological specialization diploma holders         63 (29.6%)   56 (26.3%)
Transfer                                             34 (44.2%)   11 (14.3%)

Target                                                  Graduate
Application mode_label
1st phase - general contingent                      1063 (62.2%)
1st phase - special contingent (Azores Island)         6 (37.5%)
1st phase - special contingent (Madeira Island)       25 (65.8%)
2nd phase - general contingent                       457 (52.4%)
3rd phase - general contingent                        63 (50.8%)
Change of course                                     122 (39.1%)
Change of institution/course                          26 (44.1%)
Change of institution/course (International)          1 (100.0%)
Holders of other higher courses                       47 (33.8%)
International student (bachelor)                      15 (50.0%)
Ordinance No. 533-A/99 item b2 (Different Plan)         0 (0.0%)
Ordinance No. 533-A/99 item b3 (Other Institution)      0 (0.0%)
Ordinance No. 612/93                                   1 (33.3%)
Ordinance No. 854-B/99                                 7 (70.0%)
Over 23 years old                                    229 (29.2%)
Short cycle diploma holders                           21 (60.0%)
Technological specialization diploma holders          94 (44.1%)
Transfer                                              32 (41.6%)

Target                                    Dropout     Enrolled     Graduate
Course_label
Advertising and Marketing Management   95 (35.4%)   48 (17.9%)  125 (46.6%)
Agronomy                               86 (41.0%)   37 (17.6%)   87 (41.4%)
Animation and Multimedia Design        82 (38.1%)   37 (17.2%)   96 (44.7%)
Basic Education                        85 (44.3%)   50 (26.0%)   57 (29.7%)
Biofuel Production Technologies         8 (66.7%)    3 (25.0%)     1 (8.3%)
Communication Design                   51 (22.6%)   42 (18.6%)  133 (58.8%)
Equinculture                           78 (55.3%)   21 (14.9%)   42 (29.8%)
Informatics Engineering                92 (54.1%)   64 (37.6%)    14 (8.2%)
Journalism and Communication          101 (30.5%)   34 (10.3%)  196 (59.2%)
Management                            134 (35.3%)  108 (28.4%)  138 (36.3%)
Management (evening attendance)       136 (50.7%)   54 (20.1%)   78 (29.1%)
Nursing                               118 (15.4%)  100 (13.1%)  548 (71.5%)
Oral Hygiene                           33 (38.4%)   17 (19.8%)   36 (41.9%)
Social Service                         65 (18.3%)   42 (11.8%)  248 (69.9%)
Social Service (evening attendance)    71 (33.0%)    21 (9.8%)  123 (57.2%)
Tourism                                96 (38.1%)   41 (16.3%)  115 (45.6%)
Veterinary Nursing                     90 (26.7%)   75 (22.3%)  172 (51.0%)

Target                                      Dropout     Enrolled      Graduate
Previous qualification_label
10th year                                1 (100.0%)     0 (0.0%)      0 (0.0%)
10th year - not completed                 1 (50.0%)     0 (0.0%)     1 (50.0%)
11th year - not completed                 3 (75.0%)     0 (0.0%)     1 (25.0%)
12th year - not completed               11 (100.0%)     0 (0.0%)      0 (0.0%)
Basic education 2nd cycle                 3 (42.9%)    1 (14.3%)     3 (42.9%)
Basic education 3rd cycle               104 (64.2%)    13 (8.0%)    45 (27.8%)
Frequency of higher education             7 (43.8%)     1 (6.2%)     8 (50.0%)
Higher education - bachelor's degree     16 (69.6%)     1 (4.3%)     6 (26.1%)
Higher education - degree                75 (59.5%)     4 (3.2%)    47 (37.3%)
Higher education - degree (1st cycle)    14 (35.0%)    6 (15.0%)    20 (50.0%)
Higher education - doctorate             1 (100.0%)     0 (0.0%)      0 (0.0%)
Higher education - master (2nd cycle)     2 (33.3%)     0 (0.0%)     4 (66.7%)
Higher education - master's               4 (50.0%)    1 (12.5%)     3 (37.5%)
Other - 11th year                        26 (57.8%)    6 (13.3%)    13 (28.9%)
Professional higher technical course      6 (16.7%)    8 (22.2%)    22 (61.1%)
Secondary education                    1078 (29.0%)  698 (18.8%)  1941 (52.2%)
Technological specialization course      69 (31.5%)   55 (25.1%)    95 (43.4%)

Target                  Dropout     Enrolled      Graduate
Nacionality_label
Angolan               1 (50.0%)    1 (50.0%)      0 (0.0%)
Brazilian            14 (36.8%)    6 (15.8%)    18 (47.4%)
Cape Verdean          4 (30.8%)     1 (7.7%)     8 (61.5%)
Colombian            1 (100.0%)     0 (0.0%)      0 (0.0%)
Cuban                  0 (0.0%)   1 (100.0%)      0 (0.0%)
Dutch                  0 (0.0%)     0 (0.0%)    1 (100.0%)
English                0 (0.0%)     0 (0.0%)    1 (100.0%)
German                 0 (0.0%)     0 (0.0%)    2 (100.0%)
Guinean               1 (20.0%)     0 (0.0%)     4 (80.0%)
Italian                0 (0.0%)     0 (0.0%)    3 (100.0%)
Lithuanian           1 (100.0%)     0 (0.0%)      0 (0.0%)
Mexican               1 (50.0%)     0 (0.0%)     1 (50.0%)
Moldova               2 (66.7%)    1 (33.3%)      0 (0.0%)
Mozambican             0 (0.0%)    1 (50.0%)     1 (50.0%)
Portuguese         1389 (32.2%)  770 (17.8%)  2155 (50.0%)
Romanian               0 (0.0%)    1 (50.0%)     1 (50.0%)
Russian               1 (50.0%)    1 (50.0%)      0 (0.0%)
Santomean              1 (7.1%)    5 (35.7%)     8 (57.1%)
Spanish               4 (30.8%)    5 (38.5%)     4 (30.8%)
Turkish                0 (0.0%)   1 (100.0%)      0 (0.0%)
Ukrainian             1 (33.3%)     0 (0.0%)     2 (66.7%)

Target                                        Dropout     Enrolled  \
Mother's qualification_label
10th Year                                   1 (50.0%)     0 (0.0%)
11th Year - Not Completed                   2 (66.7%)     0 (0.0%)
12th Year - Not Completed                   5 (62.5%)     0 (0.0%)
2nd cycle general high school              1 (100.0%)     0 (0.0%)
7th Year                                     0 (0.0%)     0 (0.0%)
7th Year (Old)                              2 (66.7%)     0 (0.0%)
8th Year                                    1 (33.3%)     0 (0.0%)
9th Year - Not Completed                    1 (33.3%)     0 (0.0%)
Basic Education 2nd Cycle                 140 (24.9%)   91 (16.2%)
Basic Education 3rd Cycle                 271 (28.4%)  176 (18.5%)
Basic education 1st cycle                 383 (38.0%)  169 (16.7%)
Can read without 4th year                   2 (66.7%)     0 (0.0%)
Can't read or write                         2 (66.7%)     0 (0.0%)
Frequency of Higher Education               3 (75.0%)     0 (0.0%)
General commerce course                    1 (100.0%)     0 (0.0%)
Higher Education - Bachelor's              20 (24.1%)   23 (27.7%)
Higher Education - Degree                 139 (31.7%)  101 (23.1%)
Higher Education - Doctorate                8 (38.1%)    5 (23.8%)
Higher Education - Doctorate (3rd cycle)   1 (100.0%)     0 (0.0%)
Higher Education - Master (2nd cycle)       1 (25.0%)    1 (25.0%)
Higher Education - Master's                 8 (16.3%)   15 (30.6%)
Higher education - degree (1st cycle)       3 (33.3%)    1 (11.1%)
Other - 11th Year                          22 (52.4%)     3 (7.1%)
Professional higher technical               2 (50.0%)     0 (0.0%)
Secondary Education - 12th Year           300 (28.1%)  204 (19.1%)
Specialized higher studies                  2 (33.3%)     0 (0.0%)
Technical-professional course                0 (0.0%)     0 (0.0%)
Technological specialization                4 (50.0%)    2 (25.0%)
Unknown                                    96 (73.8%)     3 (2.3%)

Target                                       Graduate
Mother's qualification_label
10th Year                                   1 (50.0%)
11th Year - Not Completed                   1 (33.3%)
12th Year - Not Completed                   3 (37.5%)
2nd cycle general high school                0 (0.0%)
7th Year                                   1 (100.0%)
7th Year (Old)                              1 (33.3%)
8th Year                                    2 (66.7%)
9th Year - Not Completed                    2 (66.7%)
Basic Education 2nd Cycle                 331 (58.9%)
Basic Education 3rd Cycle                 506 (53.1%)
Basic education 1st cycle                 457 (45.3%)
Can read without 4th year                   1 (33.3%)
Can't read or write                         1 (33.3%)
Frequency of Higher Education               1 (25.0%)
General commerce course                      0 (0.0%)
Higher Education - Bachelor's              40 (48.2%)
Higher Education - Degree                 198 (45.2%)
Higher Education - Doctorate                8 (38.1%)
Higher Education - Doctorate (3rd cycle)     0 (0.0%)
Higher Education - Master (2nd cycle)       2 (50.0%)
Higher Education - Master's                26 (53.1%)
Higher education - degree (1st cycle)       5 (55.6%)
Other - 11th Year                          17 (40.5%)
Professional higher technical               2 (50.0%)
Secondary Education - 12th Year           565 (52.9%)
Specialized higher studies                  4 (66.7%)
Technical-professional course              1 (100.0%)
Technological specialization                2 (25.0%)
Unknown                                    31 (23.8%)

Target                                           Dropout     Enrolled  \
Father's qualification_label
10th Year                                      1 (25.0%)     0 (0.0%)
11th Year - Not Completed                     2 (100.0%)     0 (0.0%)
12th Year - Not Completed                      1 (20.0%)     0 (0.0%)
2nd cycle general high school                 1 (100.0%)     0 (0.0%)
2nd year complementary high school            1 (100.0%)     0 (0.0%)
7th Year                                       1 (50.0%)     0 (0.0%)
7th Year (Old)                                 4 (40.0%)     0 (0.0%)
8th Year                                       1 (25.0%)    1 (25.0%)
9th Year - Not Completed                      3 (100.0%)     0 (0.0%)
Administration and Commerce                   1 (100.0%)     0 (0.0%)
Basic Education 2nd Cycle                    167 (23.8%)  127 (18.1%)
Basic Education 3rd Cycle                    264 (27.3%)  183 (18.9%)
Basic education 1st cycle                    432 (35.7%)  199 (16.5%)
Can read without 4th year                      5 (62.5%)     0 (0.0%)
Can't read or write                           2 (100.0%)     0 (0.0%)
Complementary High School - Not concluded     1 (100.0%)     0 (0.0%)
Complementary High School Course              1 (100.0%)     0 (0.0%)
Frequency of Higher Education                 2 (100.0%)     0 (0.0%)
General commerce course                       1 (100.0%)     0 (0.0%)
Higher Education - Bachelor's                 22 (32.4%)   25 (36.8%)
Higher Education - Degree                     90 (31.9%)   62 (22.0%)
Higher Education - Doctorate                  10 (55.6%)    3 (16.7%)
Higher Education - Doctorate (3rd cycle)      1 (100.0%)     0 (0.0%)
Higher Education - Master (2nd cycle)           0 (0.0%)     0 (0.0%)
Higher Education - Master's                   14 (35.9%)    7 (17.9%)
Higher education - degree (1st cycle)          3 (60.0%)     0 (0.0%)
Other - 11th Year                             14 (36.8%)    4 (10.5%)
Professional higher technical                   0 (0.0%)     0 (0.0%)
Secondary Education - 12th Year              281 (31.1%)  172 (19.0%)
Specialized higher studies                     1 (50.0%)    1 (50.0%)
Supplementary Accounting and Administration   1 (100.0%)     0 (0.0%)
Technical-professional course                 4 (100.0%)     0 (0.0%)
Technological specialization                   8 (40.0%)    7 (35.0%)
Unknown                                       81 (72.3%)     3 (2.7%)

Target                                          Graduate
Father's qualification_label
10th Year                                      3 (75.0%)
11th Year - Not Completed                       0 (0.0%)
12th Year - Not Completed                      4 (80.0%)
2nd cycle general high school                   0 (0.0%)
2nd year complementary high school              0 (0.0%)
7th Year                                       1 (50.0%)
7th Year (Old)                                 6 (60.0%)
8th Year                                       2 (50.0%)
9th Year - Not Completed                        0 (0.0%)
Administration and Commerce                     0 (0.0%)
Basic Education 2nd Cycle                    408 (58.1%)
Basic Education 3rd Cycle                    521 (53.8%)
Basic education 1st cycle                    578 (47.8%)
Can read without 4th year                      3 (37.5%)
Can't read or write                             0 (0.0%)
Complementary High School - Not concluded       0 (0.0%)
Complementary High School Course                0 (0.0%)
Frequency of Higher Education                   0 (0.0%)
General commerce course                         0 (0.0%)
Higher Education - Bachelor's                 21 (30.9%)
Higher Education - Degree                    130 (46.1%)
Higher Education - Doctorate                   5 (27.8%)
Higher Education - Doctorate (3rd cycle)        0 (0.0%)
Higher Education - Master (2nd cycle)         2 (100.0%)
Higher Education - Master's                   18 (46.2%)
Higher education - degree (1st cycle)          2 (40.0%)
Other - 11th Year                             20 (52.6%)
Professional higher technical                 1 (100.0%)
Secondary Education - 12th Year              451 (49.9%)
Specialized higher studies                      0 (0.0%)
Supplementary Accounting and Administration     0 (0.0%)
Technical-professional course                   0 (0.0%)
Technological specialization                   5 (25.0%)
Unknown                                       28 (25.0%)

Target                                         Dropout     Enrolled  \
Mother's occupation_label
Accounting and registry operators             0 (0.0%)    2 (66.7%)
Administrative staff                       248 (30.4%)  147 (18.0%)
Administrative support                        0 (0.0%)    2 (33.3%)
Agriculture/Fisheries Skilled Workers       26 (28.6%)   14 (15.4%)
Armed Forces                                 1 (25.0%)    2 (50.0%)
Blank                                       13 (76.5%)    2 (11.8%)
Cleaning workers                              0 (0.0%)   11 (42.3%)
Directors and Executive Managers            39 (38.2%)   15 (14.7%)
Food/clothing industry workers               1 (20.0%)    2 (40.0%)
Health professionals                          0 (0.0%)   2 (100.0%)
Health technicians                            0 (0.0%)    2 (66.7%)
ICT Specialists                               0 (0.0%)     0 (0.0%)
Industry and Construction Skilled Workers   80 (29.4%)   48 (17.6%)
Intellectual and Scientific Specialists    102 (32.1%)   78 (24.5%)
Intermediate Level Technicians              95 (27.1%)   79 (22.5%)
Legal/social/cultural technicians            1 (25.0%)    2 (50.0%)
Machine Operators                           15 (41.7%)    7 (19.4%)
Meal preparation assistants                   1 (9.1%)    7 (63.6%)
Office workers                                0 (0.0%)    4 (50.0%)
Other Situation                             51 (72.9%)     0 (0.0%)
Personal care workers                         0 (0.0%)     0 (0.0%)
Personal service workers                      0 (0.0%)    1 (33.3%)
Printing and craft workers                    0 (0.0%)   1 (100.0%)
Science and engineering technicians           0 (0.0%)   1 (100.0%)
Sellers                                       0 (0.0%)    1 (50.0%)
Service and Sales Workers                  156 (29.4%)   94 (17.7%)
Skilled construction workers                  0 (0.0%)     0 (0.0%)
Student                                     99 (68.8%)     1 (0.7%)
Teachers                                     2 (28.6%)    2 (28.6%)
Unskilled Workers                          490 (31.1%)  264 (16.7%)
Unskilled agriculture workers                 0 (0.0%)    3 (60.0%)
Unskilled industry workers                   1 (25.0%)     0 (0.0%)

Target                                        Graduate
Mother's occupation_label
Accounting and registry operators            1 (33.3%)
Administrative staff                       422 (51.7%)
Administrative support                       4 (66.7%)
Agriculture/Fisheries Skilled Workers       51 (56.0%)
Armed Forces                                 1 (25.0%)
Blank                                        2 (11.8%)
Cleaning workers                            15 (57.7%)
Directors and Executive Managers            48 (47.1%)
Food/clothing industry workers               2 (40.0%)
Health professionals                          0 (0.0%)
Health technicians                           1 (33.3%)
ICT Specialists                             1 (100.0%)
Industry and Construction Skilled Workers  144 (52.9%)
Intellectual and Scientific Specialists    138 (43.4%)
Intermediate Level Technicians             177 (50.4%)
Legal/social/cultural technicians            1 (25.0%)
Machine Operators                           14 (38.9%)
Meal preparation assistants                  3 (27.3%)
Office workers                               4 (50.0%)
Other Situation                             19 (27.1%)
Personal care workers                       2 (100.0%)
Personal service workers                     2 (66.7%)
Printing and craft workers                    0 (0.0%)
Science and engineering technicians           0 (0.0%)
Sellers                                      1 (50.0%)
Service and Sales Workers                  280 (52.8%)
Skilled construction workers                1 (100.0%)
Student                                     44 (30.6%)
Teachers                                     3 (42.9%)
Unskilled Workers                          823 (52.2%)
Unskilled agriculture workers                2 (40.0%)
Unskilled industry workers                   3 (75.0%)

Target                                         Dropout     Enrolled  \
Father's occupation_label
Accounting and registry operators             0 (0.0%)     0 (0.0%)
Administrative and commercial directors      1 (50.0%)    1 (50.0%)
Administrative staff                       139 (36.0%)   74 (19.2%)